export 'package:practica_inventario/screens/loginScreen.dart';
export 'package:practica_inventario/screens/menuRegistrosScreen.dart';
export 'package:practica_inventario/screens/menuScreen.dart';
export 'package:practica_inventario/screens/ferretScreen.dart';
export 'package:practica_inventario/screens/supplierScreen.dart';
export 'package:practica_inventario/screens/salesScreen.dart';
export 'package:practica_inventario/screens/clienteScreen.dart';
export 'package:practica_inventario/screens/lists/lists.dart';
export 'package:practica_inventario/screens/loginScreen2.dart';